name: SQL Actions Windows

on:
  workflow_dispatch:
    inputs:
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:

  build-and-deploy:
    runs-on: windows-latest
    services:
      sql:
        image: microsoft/mssql-server-windows-developer
        ports:
          - 1433:1433
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
